const rawNonCompanions = [
  { plantId: 14, nonCompanionId: 15 },
  { plantId: 14, nonCompanionId: 5 },
  { plantId: 14, nonCompanionId: 24 },
  { plantId: 14, nonCompanionId: 27 },
  { plantId: 14, nonCompanionId: 29 },
  { plantId: 15, nonCompanionId: 14 },
  { plantId: 19, nonCompanionId: 7 },
  { plantId: 19, nonCompanionId: 30 },
  { plantId: 5, nonCompanionId: 14 },
  { plantId: 5, nonCompanionId: 14 },
  { plantId: 21, nonCompanionId: 35 },
  { plantId: 22, nonCompanionId: 30 },
  { plantId: 7, nonCompanionId: 19 },
  { plantId: 7, nonCompanionId: 19 },
  { plantId: 24, nonCompanionId: 14 },
  { plantId: 9, nonCompanionId: 11 },
  { plantId: 27, nonCompanionId: 14 },
  { plantId: 27, nonCompanionId: 28 },
  { plantId: 11, nonCompanionId: 9 },
  { plantId: 28, nonCompanionId: 5 },
  { plantId: 28, nonCompanionId: 27 },
  { plantId: 29, nonCompanionId: 14 },
  { plantId: 30, nonCompanionId: 19 },
  { plantId: 30, nonCompanionId: 19 },
  { plantId: 30, nonCompanionId: 19 },
  { plantId: 30, nonCompanionId: 33 },
  { plantId: 30, nonCompanionId: 36 },
  { plantId: 31, nonCompanionId: 36 },
  { plantId: 32, nonCompanionId: 30 },
  { plantId: 33, nonCompanionId: 30 },
  { plantId: 35, nonCompanionId: 21 },
  { plantId: 35, nonCompanionId: 7 },
  { plantId: 36, nonCompanionId: 30 },
  { plantId: 36, nonCompanionId: 31 },
];

export default rawNonCompanions;
